[template]
src = "shadowsocks.json.tmpl"
dest = "/etc/shadowsocks/client.json"
keys = [
    "/services/shadowsocks"
]
check_cmd = "jq . {{.src}}"
reload_cmd = "systemctl restart shadowsocks-libev@client"
