# https://etcd.io/docs/v3.4.0/op-guide/container/

version: "3.8"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.8
    command: >
      etcd --name=node1
           --data-dir=/data
           --initial-advertise-peer-urls=http://1.2.3.4:2380
           --listen-peer-urls=http://0.0.0.0:2380
           --advertise-client-urls=http://1.2.3.4:2379
           --listen-client-urls=http://0.0.0.0:2379
           --initial-cluster=node1=http://1.2.3.4:2380
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - ./data:/data
    restart: unless-stopped
