version: '3.6'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/ssl:/etc/nginx/ssl
#    net: host
    restart: always

networks:
  default:
    external:
      name: localhost

