version: "3.8"

services:

  webdis:
    image: vimagick/webdis
    ports:
      - "7379:7379"
    volumes:
      - ./data/webdis:/etc/webdis
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    command: --save 900 1
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
