version: "3.8"
services:
  owncast:
    image: gabekangas/owncast
    command: /app/owncast --configFile=/data/config.yaml --database=/data/chat.db
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./data:/data
    restart: unless-stopped
