version: "3.8"

services:

  prestashop:
    image: prestashop/prestashop:1.7-apache
    ports:
      - "8080:80"
    volumes:
      - ./data/prestashop:/var/www/html
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mariadb:10
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop
    restart: unless-stopped
