fteproxy:
  image: easypi/fteproxy-arm
  ports:
    - "1194:1194"
  environment:
    - MODE=client
    - SERVER_IP=vpn.easypi.info
    - SERVER_PORT=4911
    - CLIENT_IP=0.0.0.0
    - CLIENT_PORT=1194
    - KEY=66754b8113ea7a218b7613f73f7e13b1e91790216f659b5f78b903b34c654741
  restart: always
