version: "3"
services:

  # Ref: https://github.com/zaproxy/zaproxy/wiki/Docker
  # Ref: https://github.com/zaproxy/zap-api-go/tree/master/example
  # Ref: https://github.com/zaproxy/zaproxy/wiki/WebSwing
  # Ref: https://github.com/zaproxy/zap-core-help/wiki/HelpCmdline
  zaproxy:
#    image: owasp/zap2docker-bare
    image: owasp/zap2docker-stable
    command: [
#      "zap.sh", # headless
#      "zap-x.sh",
      "zap-webswing.sh", # web
      "-daemon",
      "-host", "0.0.0.0", "-port", "8080",
      "-config", "api.disablekey=true",
      "-config", "api.addrs.addr.name=.*",
      "-config", "api.addrs.addr.regex=true"
#      "-addoninstall FOOXYZ",
#      "-addonupdate"
    ]
    ports:
      - "8080:8080"
      - "8090:8090"
    # environment:
    #   ZAP_PORT: 8083
#    volumes:
#      - "/tmp/.X11-unix:/tmp/.X11-unix"
#      - "${HOME}/.Xauthority:/home/zap/.Xauthority"
#    environment:
#      DISPLAY: "${IP}:0"

  # Ref: https://github.com/psiinon/bodgeit
  bodgeit:
    image: psiinon/bodgeit:latest
    ports:
      - "8081:8080"

  # Ref: https://github.com/bkimminich/juice-shop
  # Ref: http://help.owasp-juice.shop
  juiceshop:
    image: bkimminich/juice-shop:latest
    ports:
      - "8082:3000"


networks:
  default:
    external:
      name: localhost
