version: "3.8"

services:

  navidrome:
    image: deluan/navidrome:develop
    ports:
      - "4533:4533"
    volumes:
      - ./data:/data
      - ./music:/music:ro
    environment:
      - ND_SCANINTERVAL=1h
      - ND_SESSIONTIMEOUT=24h
      - ND_LOGLEVEL=info
      - ND_BASEURL=
    user: "1000:1000"
    restart: unless-stopped
