dnsmasq:
  image: easypi/dnsmasq-arm
  volumes:
    - ./dnsmasq.conf:/etc/dnsmasq.d/dnsmasq.conf
  net: container:dnscrypt
  restart: always

dnscrypt:
  image: easypi/dnscrypt-proxy-arm
  command: dnscrypt-proxy -a 127.0.0.1:2053 -R cisco
  ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "67:67/udp"
  cap_add:
    - NET_ADMIN
  restart: always
