version: "3.8"

services:

  polipo:
    image: vimagick/polipo
    networks:
      - host_network
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure

networks:
  host_network:
    external: true
    name: host
