etcd:
  image: vimagick/etcd-arm
  command: |
    -name pi2
    -data-dir=/var/lib/etcd
    -listen-client-urls http://0.0.0.0:2379
    -advertise-client-urls http://192.168.1.229:2379
    -listen-peer-urls http://0.0.0.0:2380
    -initial-advertise-peer-urls http://192.168.1.229:2380
    -initial-cluster-token pi-cluster
    -initial-cluster pi0=http://192.168.1.228:2380,pi1=http://192.168.1.207:2380,pi2=http://192.168.1.229:2380
    -initial-cluster-state new
  ports:
    - "2379:2379"
    - "2380:2380"
  volumes:
    - /var/lib/etcd
  restart: always
