data:
  build: .
  entrypoint: /bin/true

service:
  image: debian:jessie
  command: >
    ./ngrokd
    -domain=ngrok.foobar.site
    -httpAddr=:2080
    -httpsAddr=:2443
    -tunnelAddr=:4443
    -tlsCrt=snakeoil.crt
    -tlsKey=snakeoil.key
    -log-level=INFO
  ports:
    - "2080:2080"
    - "2443:2443"
    - "4443:4443"
  volumes_from:
    - data
  working_dir: /ngrok
  restart: always
