version: "3.8"

services:

  mpd:
    image: easypi/mpd-arm
    ports:
      - "6600:6600"
      - "8800:8800"
    volumes:
      - ./data/config:/root/.config
      - ./data/music:/var/lib/mpd/music
      - ./data/playlists:/var/lib/mpd/playlists
    devices:
      - /dev/snd
#   depends_on:
#     - icecast
    restart: unless-stopped

# icecast:
#   image: vimagick/icecast
#   ports:
#     - "8000:8000"
#   restart: unless-stopped
