phpmyadmin:
  image: easypi/phpmyadmin-arm
  ports:
    - "8080:80"
  environment:
    - PMA_HOST=mysql
    - PMA_PORT=3306
  links:
    - mysql
  restart: always

mysql:
  image: easypi/mariadb-arm
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=wordpress
  restart: always
