version: "3.7"
services:
  pihole:
    image: pihole/pihole:v4.4-armhf
    ports:
      - "53:53/udp"
      - "80:80/tcp"
    volumes:
      - ./data/pihole:/etc/pihole
      - ./data/dnsmasq.d:/etc/dnsmasq.d
    environment:
      - TZ=Asia/Shanghai
      - WEBPASSWORD=******
      - DNS1=172.18.0.1#5300
      - DNS2=no
    restart: unless-stopped
