frps:
  image: vimagick/frp
  ports:
    - "7000:7000/tcp"
    - "7000:7000/udp"
    - "7500:7500/tcp"
    - "127.0.0.1:20000-20099:20000-20099/tcp"
  volumes:
    - ./data/frps.ini:/opt/frp/frps.ini
  restart: always
