version: "3.7"

services:

  ksqldb-server:
    image: confluentinc/ksqldb-server:0.6.0
    ports:
      - "8088:8088"
    environment:
      - KSQL_LISTENERS=http://0.0.0.0:8088
      - KSQL_BOOTSTRAP_SERVERS=kafka:9092
      - KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE=true
      - KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE=true
      - KSQL_KSQL_CONNECT_WORKER_CONFIG=/data/connect.properties
      # KSQL_KSQL_CONNECT_URL=kafka-connect:8083
      # KSQL_KSQL_SCHEMA_REGISTRY_URL=http://schema-registry:8081
    volumes:
      - ./data:/data
    restart: unless-stopped

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.6.0
    entrypoint: /bin/sh
    tty: true
    depends_on:
      - ksqldb-server

  kafkacat:
    image: confluentinc/cp-kafkacat:5.4.0
    entrypoint: /bin/sh
    tty: true
    depends_on:
      - kafka
