prosody:
  image: prosody/prosody
  ports:
    - "5222:5222"
    - "5280:5280"
  volumes:
    - ./data/etc:/etc/prosody:ro
    - ./data/log:/var/log/prosody:rw
    - ./data/var:/var/lib/prosody:rw
  restart: unless-stopped
