version: "3.8"
services:
  ndscheduler:
    image: vimagick/ndscheduler
    ports:
      - "8888:8888"
    volumes:
      - ./data:/opt/ndscheduler
    environment:
      - PYTHONPATH=/opt/ndscheduler
      - NDSCHEDULER_SETTINGS_MODULE=settings
    restart: unless-stopped
