openvpn:
  image: kylemanna/openvpn
  ports:
    - "1194:1194"
  volumes:
    - ./data:/etc/openvpn
  cap_add:
    - NET_ADMIN
  restart: always

stunnel:
  image: vimagick/stunnel
  ports:
    - "4911:4911"
  links:
    - openvpn
  environment:
    - CLIENT=no
    - SERVICE=openvpn
    - ACCEPT=0.0.0.0:4911
    - CONNECT=openvpn:1194
  restart: always
