elasticsearch:
  image: easypi/elasticsearch-arm
  ports:
    - '9200:9200'
    - '9300:9300'
  volumes:
    - ./data:/opt/elasticsearch/data
    - ./config:/opt/elasticsearch/config
  mem_limit: 4g
  cap_add:
    - IPC_LOCK
  restart: always
