version: "3.8"

services:

  oss:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    command: gateway oss https://oss-cn-beijing.aliyuncs.com
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=ossaccesskey
      - MINIO_SECRET_KEY=osssecretkey
    restart: unless-stopped

  s3:
    image: minio/minio
    command: gateway s3
    ports:
      - "9001:9000"
    environment:
      - MINIO_ACCESS_KEY=awsaccesskey
      - MINIO_SECRET_KEY=awssecretkey
    restart: unless-stopped

  nas:
    image: minio/minio
    command: gateway nas /data
    ports:
      - "9002:9000"
    volumes:
      - ./data:/data
    environment:
      - MINIO_ACCESS_KEY=nasaccesskey
      - MINIO_SECRET_KEY=nassecretkey
    restart: unless-stopped
