statsd:
  image: vimagick/statsd
  ports:
    - "8126:8126/tcp"
    - "8125:8125/udp"
  volumes:
    - ./data/config.js:/opt/statsd/config.js
  external_links:
    - graphite_graphite_1:graphite
  restart: always
