version: '3.6'

services:
  jenkins:
    image: jenkins/jenkins:lts-alpine
    ports:
      - "8085:8080"
#      - "50000:50000"
    volumes:
      - ./data:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Dhudson.footerURL=http://jenkins.easypi.pro
    restart: always

networks:
  default:
    external:
      name: localhost


