version: "2.3.3"
services:
    mongo:
      image: mongo
      command: --auth
      container_name: mongo
      ports:
        - "27017:27017"
      volumes:
        - ./data:/data/db
      restart: always
