hub:
  image: selenium/hub
  ports:
    - "4444:4444"
  environment:
    - GRID_TIMEOUT=60
    - GRID_BROWSER_TIMEOUT=30
  restart: always

firefox:
  image: selenium/node-firefox-debug
  ports:
    - "5555"
    - "5901:5900"
  links:
    - hub
  environment:
    - JAVA_OPTS=-Xmx768m
    - SCREEN_WIDTH=1024
    - SCREEN_HEIGHT=768
    - SCREEN_DEPTH=16
    - NODE_MAX_INSTANCES=5
    - NODE_MAX_SESSION=5
  restart: always

chrome:
  image: selenium/node-chrome-debug
  ports:
    - "5555"
    - "5902:5900"
  links:
    - hub
  environment:
    - JAVA_OPTS=-Xmx768m
    - SCREEN_WIDTH=1024
    - SCREEN_HEIGHT=768
    - SCREEN_DEPTH=16
    - NODE_MAX_INSTANCES=5
    - NODE_MAX_SESSION=5
  restart: always
